#!/bin/bash

docker build \
  --build-arg BUILD_DATE="$(date --rfc-3339=s)" \
  --build-arg VCS_REF=`git rev-parse --short HEAD` \
  -t $IMAGE_NAME .

  docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
               --build-arg VCS_REF=`git rev-parse --short HEAD` \
               --build-arg VERSION=`cat VERSION` .
